#!/usr/bin/expect

set hosts [lindex $argv 0]
set port [lindex $argv 1]
set pass [lindex $argv 2]
set timeout 1

foreach host $hosts {
	spawn telnet $host $port
	expect -re ".*>"
	send "dbsize\r"
	expect {
		-exact "-NOAUTH Authentication required." {
			send "auth $pass\r"
			expect -exact "+OK"
			send "dbsize\r"
			expect -re ":.*"
			send "flushall\r"
			expect -exact "+OK"

		}
		-re ":.*" {
			send "flushall\r"
			expect -exact "+OK"
		}
	}
	send "quit\r"
	expect eof
}
